data<-read.table("power/household_power_consumption_2007.txt",sep=";",header=TRUE)
par(mfrow=c(2,2), cex=0.8, mar=c(4,5,3,3))
plot(x=strptime(paste(data$Date,data$Time),format="%d/%m/%Y %H:%M:%S"),y=data$Global_active_power,type="l",xlab=" ",ylab="Global Active Power")
plot(x=strptime(paste(data$Date,data$Time),format="%d/%m/%Y %H:%M:%S"),y=data$Voltage,type="l",xlab="date time",ylab="Voltage")
plot(x=strptime(paste(data$Date,data$Time),format="%d/%m/%Y %H:%M:%S"),col="black",y=data$Sub_metering_1,type="l",xlab=" ",ylab="Energy sub metering")
lines(x=strptime(paste(data$Date,data$Time),format="%d/%m/%Y %H:%M:%S"),col="red",y=data$Sub_metering_2,type="l")
points(x=strptime(paste(data$Date,data$Time),format="%d/%m/%Y %H:%M:%S"),col="blue",y=data$Sub_metering_3,type="l")
legend("topright", lty = 1, col = c("black", "red", "blue"), cex=0.5,bty="n", legend = c("Sub_metering_1","Sub_metering_2", "Sub_metering_3"))
plot(x=strptime(paste(data$Date,data$Time),format="%d/%m/%Y %H:%M:%S"),y=data$Global_reactive_power,type="l",xlab="date time",ylab="Global Reactive Power")
dev.copy(png,file="plot4.png")
dev.off()