data<-read.table("power/household_power_consumption_2007.txt",sep=";",header=TRUE)
par(mfrow=c(1,1))
plot(x=strptime(paste(data$Date,data$Time),format="%d/%m/%Y %H:%M:%S"),col="black",y=data$Sub_metering_1,type="l",xlab=" ",ylab="Energy sub metering")
lines(x=strptime(paste(data$Date,data$Time),format="%d/%m/%Y %H:%M:%S"),col="red",y=data$Sub_metering_2,type="l")
points(x=strptime(paste(data$Date,data$Time),format="%d/%m/%Y %H:%M:%S"),col="blue",y=data$Sub_metering_3,type="l")
legend("topright", lty = 1, col = c("black", "red", "blue"), cex=0.7, legend = c("Sub_metering_1","Sub_metering_2", "Sub_metering_3"))
dev.copy(png,file="plot3.png")
dev.off()